name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # har kuni UTC 00:00 da ishga tushadi
  workflow_dispatch: # qo'lda ham ishga tushirish imkoniyati
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Faxriyorbey571
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to dist branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
